name: deploy_netflify

on:
  push:
    branches: [ "master" ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11

      - name: Cmake Build
        run: |
          embuilder build zlib
          # embuilder build zlib --lto
          # embuilder build zlib --lto=thin
          cmake --preset emsdk -DEM_USE_THREADS=ON
          cmake --build --preset emsdk --parallel 4

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: build/emsdk/bin
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
